set(CMAKE_SYSTEM_NAME Linux )
set(triple x86_64_lfi-linux-musl )
set(CMAKE_C_COMPILER /opt/x86_64-lfi-clang/bin/clang CACHE STRING "" FORCE)
set(CMAKE_C_COMPILER_TARGET ${triple} CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER /opt/x86_64-lfi-clang/bin/clang++ CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER_TARGET ${triple} CACHE STRING "" FORCE)
set(CMAKE_SYSROOT /opt/x86_64-lfi-clang/sysroot )
set(LFI ON CACHE BOOL "")
